[package]
name = "manual"
version.workspace = true
edition.workspace = true

[dependencies]
bevy = { workspace = true }
bevy_physics = { workspace = true }
bevy_extensions = { workspace = true }
bevy_bootstrap = { workspace = true }
bevy_actions = { workspace = true }
bevy_grid = { workspace = true }
