[package]
name = "bevy_actions"
version.workspace = true
edition.workspace = true

[dependencies]
bevy = { workspace = true }
bevy_physics = { workspace = true }
bevy_extensions = { workspace = true }
bevy-sequential-actions = "0.6"
